# ~/.zshrc - Generated by Pulsar Installer
# Pulsar - Minimal Zsh Plugin Manager

# === Plugin Configuration ===
PULSAR_PLUGINS=(
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-syntax-highlighting
  OMZP::git
)
source ~/.config/zsh/lib/pulsar.zsh

# =============================================================================
# === OPTIONAL: Oh-My-Zsh Libraries (uncomment what you want) ===
# =============================================================================
#
# Pulsar supports loading OMZ libs directly! Just uncomment the ones you want.
# Full list: https://github.com/ohmyzsh/ohmyzsh/tree/master/lib
#
# Popular choices:

# PULSAR_PLUGINS+=(
#   OMZL::history                # History configuration (HIST_* options)
#   OMZL::key-bindings          # Comprehensive key bindings (arrows, Ctrl+R, etc.)
#   OMZL::completion            # Advanced completion system
#   OMZL::theme-and-appearance  # Prompt and color configurations
#   OMZL::directories           # Directory navigation aliases (cd shortcuts)
#   OMZL::git                   # Git helper functions
# )

# Or add specific OMZ libs you need:
# OMZL::clipboard              # Cross-platform clipboard helpers
# OMZL::grep                   # Grep aliases with color
# OMZL::spectrum               # 256-color support
# OMZL::termsupport            # Terminal title management

# =============================================================================
# === OR: Quick Custom Setup (if you prefer not using OMZ libs) ===
# =============================================================================

# # Basic completion
# autoload -Uz compinit && compinit
#
# # Basic history
# HISTFILE=~/.zsh_history
# HISTSIZE=10000
# SAVEHIST=10000
# setopt SHARE_HISTORY HIST_IGNORE_DUPS
#
# # Basic key bindings
# bindkey -e                                      # Emacs mode
# bindkey '^R' history-incremental-search-backward  # Ctrl+R search
#
# # Simple prompt
# PROMPT='%F{blue}%~%f %# '

# =============================================================================
# For more customization, see: https://zsh.sourceforge.io/Doc/Release/
# =============================================================================
