# ~/.zshrc - Generated by Pulsar Installer
# Pulsar - Minimal Zsh Plugin Manager

# === Plugin Configuration ===
PULSAR_PLUGINS=(
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-syntax-highlighting
  OMZP::git
)
source ~/.config/zsh/lib/pulsar.zsh

# =============================================================================
# === OPTIONAL: Oh-My-Zsh Libraries (uncomment what you want) ===
# =============================================================================
#
# Pulsar supports loading OMZ libs directly! Just uncomment the ones you want.
# Full list: https://github.com/ohmyzsh/ohmyzsh/tree/master/lib
#
# Popular choices (recommended starter pack):

# PULSAR_PLUGINS+=(
#   OMZL::history                # Persistent history with SHARE_HISTORY, deduplication, timestamps
#   OMZL::key-bindings          # Navigation (Home/End, Ctrl+arrows), history search (Ctrl+R, arrows), editing (Ctrl+W)
#   OMZL::completion            # Smart tab completion with menu selection, case-insensitive matching
#   OMZL::theme-and-appearance  # Color support, prompt helpers, LS_COLORS configuration
#   OMZL::directories           # Quick directory switching (dirs, pushd/popd stack, auto-cd)
#   OMZL::git                   # Git aliases and helper functions (git_current_branch, etc.)
# )

# Additional useful libs (pick what you need):
# OMZL::clipboard              # Clipboard integration (clipcopy, clippaste) for Linux/macOS/WSL
# OMZL::grep                   # Colorized grep with GREP_COLOR, excludes .git directories
# OMZL::spectrum               # 256-color palette support ($FG[color], $BG[color] variables)
# OMZL::termsupport            # Dynamic terminal titles showing current directory and command
# OMZL::functions              # Utility functions (take, extract, etc.)
# OMZL::compfix                # Fix insecure completion directories automatically
# OMZL::correction             # Spell correction for commands (suggests alternatives)
# OMZL::misc                   # Miscellaneous settings (URL quoting, safe rm/cp/mv)

# =============================================================================
# === OR: Quick Custom Setup (if you prefer not using OMZ libs) ===
# =============================================================================

# # Basic completion
# autoload -Uz compinit && compinit
#
# # Basic history
# HISTFILE=~/.zsh_history
# HISTSIZE=10000
# SAVEHIST=10000
# setopt SHARE_HISTORY HIST_IGNORE_DUPS
#
# # Basic key bindings
# bindkey -e                                      # Emacs mode
# bindkey '^R' history-incremental-search-backward  # Ctrl+R search
#
# # Simple prompt
# PROMPT='%F{blue}%~%f %# '

# =============================================================================
# For more customization, see: https://zsh.sourceforge.io/Doc/Release/
# =============================================================================
